<?xml version="1.0"?>
<robot name="ackermann_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 全局属性 -->
  <xacro:property name="wheelbase" value="0.21333" />
  <xacro:property name="track_width" value="0.29148" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="max_steer_angle" value="0.6" />
  
  <!-- 底色 -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  
  <!-- 底盘 -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.3 0.2 0.1"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.3 0.2 0.1"/>
      </geometry>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </inertial>
  </link>
  
  <!-- 雷达链接 -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </inertial>
  </link>
  
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>
  
  <!-- 前轮转向关节 -->
  <link name="front_steer_link">
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>
  
  <joint name="front_steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_steer_link"/>
    <origin xyz="${wheelbase/2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-max_steer_angle}" upper="${max_steer_angle}" effort="10" velocity="1"/>
  </joint>
  
  <!-- 前左轮 -->
  <link name="front_left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </inertial>
  </link>
  
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_steer_link"/>
    <child link="front_left_wheel_link"/>
    <origin xyz="0 ${track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- 前右轮 -->
  <link name="front_right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </inertial>
  </link>
  
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_steer_link"/>
    <child link="front_right_wheel_link"/>
    <origin xyz="0 ${-track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- 后左轮 -->
  <link name="rear_left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </inertial>
  </link>
  
  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- 后右轮 -->
  <link name="rear_right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </inertial>
  </link>
  
  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${-track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- Gazebo相关插件和属性 (根据需要添加) -->

</robot> 