bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: "/odom"
    bt_loop_duration: 50
    default_server_timeout: 30
    default_controller_id: "FollowPath"
    default_planner_id: "GridBased"
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 8.0  
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001  
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.5
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["ackermann_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.25  
      movement_time_allowance: 20.0   
    ackermann_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.60         
      yaw_goal_tolerance: 0.60        
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2          
      min_linear_vel: 0.08            
      max_linear_vel: 0.5             
      lookahead_dist: 0.8             
      use_velocity_scaled_lookahead_dist: true
      min_lookahead_dist: 0.4         
      max_lookahead_dist: 1.5         
      lookahead_time: 1.2             
      allow_rotate_to_heading: false   
      rotate_to_heading_angular_vel: 0.0
      use_rotate_to_heading: false
      max_allowed_time_to_collision_up_to_carrot: 2.0
      use_regulated_linear_velocity_scaling: true
      regulate_by_speed_scaling: true
      speed_scaling_dist: 0.8         
      cost_scaling_gain: 0.4          
      regulation_scaling_gain: 0.2    
      use_interpolation: true
      transform_tolerance: 0.1        
      goal_dist_thresh: 0.15
      goal_angle_thresh: 0.25
      clip_velocities: true
      allow_reversing: false          
      use_collision_detection: true
      min_obstacle_dist: 0.10          
      max_angular_velocity_angle_tolerance: 0.5
      trajectory_check_time: 2.0      
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 6.0          
      publish_frequency: 3.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      use_sim_time: False
      rolling_window: true
      width: 10                      
      height: 10
      resolution: 0.05
      transform_tolerance: 0.3       
      footprint: "[[0.08, 0.05], [0.08, -0.05], [-0.08, -0.05], [-0.08, 0.05]]"
      footprint_clearing_enabled: true
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False       
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: "/scan"
          raytrace_max_range: 10.0     
          clearing: True
          marking: True
          data_type: "LaserScan"
          obstacle_max_range: 8.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5      
        inflation_radius: 0.15        
      always_send_full_costmap: True
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.5          
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      use_sim_time: False
      transform_tolerance: 0.3
      footprint: "[[0.08, 0.05], [0.08, -0.05], [-0.08, -0.05], [-0.08, 0.05]]"
      resolution: 0.05
      track_unknown_space: true
      allow_unknown: true
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 8.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5      
        inflation_radius: 0.15        
      always_send_full_costmap: True
      width: 60
      height: 60
      origin_x: -30.0
      origin_y: -30.0
planner_server:
  ros__parameters:
    expected_planner_frequency: 6.0   
    use_sim_time: False
    planner_plugins: ["AckermannHybridAStar", "GridBased"]
    AckermannHybridAStar:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.60                  
      allow_unknown: true
      motion_model_for_search: "DUBIN"
      minimum_turning_radius: 0.3047   
      angle_quantization_bins: 180     
      analytic_expansion_max_length: 2.5
      max_iterations: 300000           
      cost_travel_multiplier: 1.0     
      cost_penalty_penalty: 1.0       
      smoothing: true                  
      downsample_costmap: false        
      debug_visualizations: false     
      allow_reverse: false             
      retrospective_penalty: 0.05     
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.60                  
      allow_unknown: true
      motion_model_for_search: "DUBIN"
      minimum_turning_radius: 0.3047   
      angle_quantization_bins: 180
      analytic_expansion_max_length: 2.5
      max_iterations: 300000           
      cost_travel_multiplier: 1.0
      cost_penalty_penalty: 1.0       
      smoothing: true
      downsample_costmap: false
      debug_visualizations: false
      allow_reverse: false
      retrospective_penalty: 0.05
smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["ackermann_smoother"]
    ackermann_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1500                   
      do_refinement: True             
behavior_server:
  ros__parameters:
    use_sim_time: False
    global_frame: "odom"
    robot_base_frame: "base_link"
    transform_tolerance: 0.3
    behavior_plugins: ["backup", "drive_on_heading", "wait", "spin"]
    backup:
      plugin: "nav2_behaviors/BackUp"
      time_allowance: 8.0             
      speed: 0.15                     
      simulate_ahead_time: 2.0        
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      time_allowance: 8.0
      speed: 0.15
      simulate_ahead_time: 2.0
    wait:
      plugin: "nav2_behaviors/Wait"
      time_allowance: 10.0
    spin:
      plugin: "nav2_behaviors/Spin"
      time_allowance: 6.0             
      simulate_ahead_time: 1.0        
      max_rotational_vel: 0.5         
      min_rotational_vel: 0.1         
      rotational_acc_lim: 0.8         
waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: true
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0
map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""
    topic_name: "map"
    frame_id: "map"
lifecycle_manager:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names:
      [
        "controller_server",
        "planner_server",
        "smoother_server",
        "behavior_server",
        "bt_navigator"
      ]
